### PR TITLE
Add initial integration tests

### LINKED ISSUE #14: Add a testing harness
Not sure what the best way of testing this is, but at the very least, we should add some known unit and record files to a directory and add some shell scripts to call the tool with different inputs.

### PR DESCRIPTION
**Pull request by kastiglione**
Adds an initial test system, based on LLVM's [`FileCheck`](https://llvm.org/docs/CommandGuide/FileCheck.html).

The test works like this:

1. Create an index by running a `clang` and `swiftc` commands
2. Run `index-import -V` and pipe the verbose output to `FileCheck` to verify unit remapping
3. Check that the expected files exist
4. Check that the record files are identical

Fixes #14

### CODE REVIEW

**Comment by kastiglione** [comment]
@ob

**Comment by kastiglione** [comment]
TODO

- [ ] Add comparable `swiftc`

**Comment by kastiglione** [comment]
Thoughts on this approach? Improvements? Alternatives?

**Comment by ob** [comment]
Nice, good starting point. We'll tweak as needed.

**Pull request merged**
